### PR TITLE
Rewrite + chat 

### PR DESCRIPTION
**Pull request by sjagoori**
DO NOT MERGE

### CODE REVIEW

**Comment by sjagoori** [comment]
**TODO**
- [ ] router.js - filter out all the chats **opened** by the user_id
- [ ] router.js - filter out all the chats **requested** by the user_id
- [ ] ioEvents.js - broadcast messages to `pair` 
- [ ] iotEvents.js - emit message cache using messageCache.js
- [ ] [chat].js - handle message history
- [ ] [chat].js - handle broadcasted messages

**Comment by sjagoori** [comment]
**TODO**
- [ ] ioEvents - prevent updating database if from.user_id exists in `{ chatData: { chats[..] } }`
- [x] router.js - filter out all the chats **opened** by the user_id
- [ ] router.js - filter out all the chats **requested** by the user_id
- [x] ioEvents.js - broadcast messages to `pair` 
- [ ] iotEvents.js - emit message cache using messageCache.js
- [?] [chat].js - handle message history
- [ ] [chat].js - handle broadcasted messages

**Comment by sjagoori** [comment]
Current state: 

What works:
* Open a room (pair) 
* Send messages to users (real-time)
* Opening a room adds an entry in `chats: []` in the database
* Opening a room renders the user in `chat.js` 

What doesn't work (yet): 
* Caching messages
* Returning a message cache
* Broadcasting in rooms
* Preventing duplicates in `chats` (database) 
* A list of requests

**Comment by sjagoori** [comment]
**TODO**

- [ ] styling in [chat].js
- [ ] styling in chat.js
- [ ] consent in requested chats

**Comment by bommezijn** [comment]
# 💄 Styling

## Pages that need styling  **(could have)**
- [ ] Chat page
- [ ] Chat box (`[chat].js`) 

## Elements / pages that need style fixing
- [ ] Navbar. Off-center  **(Must have)**
CleanShot 2021-06-16 at 23 37 13
- [ ] [Flowing effect **(could have)**](https://xd.adobe.com/view/aac8a536-559f-49d5-a689-bd368a575f1d-ff9b/screen/a5c6145b-ad84-4901-9032-8d23b9c97a57) for cancer types.
CleanShot 2021-06-16 at 23 43 00

- [ ] Labels under the labels **(could have)**
CleanShot 2021-06-16 at 23 42 40



---
# 🐛  Bugs
- [ ] Empty chat page gets _TypeError: Cannot read property 'chats' of undefined_.
https://github.com/sjagoori/bloom/blob/aa3a227bf9f6e4ceec240db6cb35928508f77044/frontend/pages/chat.js#L29

**Pull request merged**
